
import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { CheckCircle, HeartPulse, Stethoscope, School, ShieldCheck, MessageSquare, Bell, FileText } from 'lucide-react';
import { Logo } from '@/components/logo';
import { placeholderImages } from '@/lib/placeholder-images';

const features = [
  {
    icon: <Stethoscope className="size-8 text-primary" />,
    title: 'Smart Doctor Directory',
    description: 'Easily find and connect with specialized doctors from our verified directory.',
  },
  {
    icon: <CheckCircle className="size-8 text-primary" />,
    title: 'Effortless Appointments',
    description: 'Book, manage, and attend appointments with a few simple clicks.',
  },
  {
    icon: <HeartPulse className="size-8 text-primary" />,
    title: 'Personalized Health Timeline',
    description: 'Keep track of your medical history, reports, and prescriptions all in one place.',
  },
  {
    icon: <School className="size-8 text-primary" />,
    title: 'Student Learning Hub',
    description: 'Access curated medical content and find internship opportunities.',
  },
  {
    icon: <FileText className="size-8 text-primary" />,
    title: 'AI-Powered Summaries',
    description: 'Get concise summaries of your consultations, generated by our advanced AI.',
  },
  {
    icon: <Bell className="size-8 text-primary" />,
    title: 'Medication Reminders',
    description: 'Never miss a dose with our intelligent medication reminder system.',
  },
];

const testimonials = [
  {
    name: 'Priya Sharma',
    role: 'Patient',
    avatar: 'PS',
    image: placeholderImages.find(p => p.id === 'avatar-1')?.imageUrl,
    text: 'NirogTech made it so easy to find a specialist for my condition. The video consultation was seamless and saved me hours of travel.',
  },
  {
    name: 'Dr. Arjun Mehta',
    role: 'Cardiologist',
    avatar: 'AM',
    image: placeholderImages.find(p => p.id === 'avatar-2')?.imageUrl,
    text: 'The platform is incredibly intuitive. It simplifies my workflow and the AI summary tool is a game-changer for my note-taking.',
  },
  {
    name: 'Rohan Verma',
    role: 'Medical Student',
    avatar: 'RV',
    image: placeholderImages.find(p => p.id === 'avatar-3')?.imageUrl,
    text: 'The learning hub is a fantastic resource, and I was able to find a great internship through the matching system. Highly recommend!',
  },
];

export default function Home() {
  const heroImage = placeholderImages.find(p => p.id === 'hero');

  return (
    <div className="flex flex-col min-h-screen">
      <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-16 items-center">
          <Link href="/" className="flex items-center gap-2">
            <Logo className="size-8 text-primary" />
            <span className="font-headline text-2xl font-bold text-foreground">NirogTech</span>
          </Link>
          <nav className="ml-auto flex items-center gap-4">
            <Button variant="ghost" asChild>
              <Link href="/login">Sign In</Link>
            </Button>
            <Button asChild>
              <Link href="/signup">Get Started</Link>
            </Button>
          </nav>
        </div>
      </header>

      <main className="flex-1">
        <section className="relative py-20 md:py-32">
          {heroImage && (
             <Image
                src={heroImage.imageUrl}
                alt={heroImage.description}
                fill
                className="object-cover"
                priority
                data-ai-hint={heroImage.imageHint}
              />
          )}
          <div className="absolute inset-0 bg-gradient-to-t from-background via-background/80 to-transparent"></div>
          <div className="container relative text-center">
            <h1 className="font-headline text-4xl font-bold tracking-tight text-foreground sm:text-5xl md:text-6xl lg:text-7xl">
              Your Health, <span className="text-primary">Reimagined.</span>
            </h1>
            <p className="mt-6 max-w-3xl mx-auto text-lg text-muted-foreground md:text-xl">
              Seamlessly connect with doctors, manage your health, and empower your medical journey with NirogTech.
            </p>
            <div className="mt-10 flex justify-center gap-4">
              <Button size="lg" asChild>
                <Link href="/signup">Book an Appointment</Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <Link href="/signup">I'm a Doctor</Link>
              </Button>
            </div>
          </div>
        </section>

        <section id="features" className="py-20 sm:py-28 bg-background">
          <div className="container">
            <div className="text-center">
              <h2 className="font-headline text-3xl font-bold text-foreground sm:text-4xl">A New Standard in Telehealth</h2>
              <p className="mt-4 max-w-2xl mx-auto text-muted-foreground">
                Everything you need for a modern healthcare experience, right at your fingertips.
              </p>
            </div>
            <div className="mt-16 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
              {features.map((feature) => (
                <Card key={feature.title} className="text-center">
                  <CardHeader>
                    <div className="mx-auto flex size-14 items-center justify-center rounded-full bg-primary/10">
                      {feature.icon}
                    </div>
                    <CardTitle className="mt-4 font-headline">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        <section id="how-it-works" className="py-20 sm:py-28">
           <div className="container">
              <div className="text-center">
                  <h2 className="font-headline text-3xl font-bold text-foreground sm:text-4xl">Simple Steps to Better Health</h2>
                  <p className="mt-4 max-w-2xl mx-auto text-muted-foreground">Getting started with NirogTech is quick and easy.</p>
              </div>
              <div className="mt-16 grid gap-12 md:grid-cols-3">
                  <div className="flex flex-col items-center text-center">
                      <div className="flex items-center justify-center size-20 rounded-full border-2 border-primary text-primary font-bold text-2xl font-headline">1</div>
                      <h3 className="mt-6 text-xl font-headline font-semibold">Create Your Account</h3>
                      <p className="mt-2 text-muted-foreground">Sign up as a patient, doctor, or student to get personalized access.</p>
                  </div>
                  <div className="flex flex-col items-center text-center">
                      <div className="flex items-center justify-center size-20 rounded-full border-2 border-primary text-primary font-bold text-2xl font-headline">2</div>
                      <h3 className="mt-6 text-xl font-headline font-semibold">Find Your Doctor</h3>
                      <p className="mt-2 text-muted-foreground">Browse our directory and book an appointment that fits your schedule.</p>
                  </div>
                  <div className="flex flex-col items-center text-center">
                      <div className="flex items-center justify-center size-20 rounded-full border-2 border-primary text-primary font-bold text-2xl font-headline">3</div>
                      <h3 className="mt-6 text-xl font-headline font-semibold">Start Your Consultation</h3>
                      <p className="mt-2 text-muted-foreground">Connect with your doctor via secure video call from anywhere.</p>
                  </div>
              </div>
           </div>
        </section>

        <section id="testimonials" className="py-20 sm:py-28 bg-background">
          <div className="container">
            <div className="text-center">
              <h2 className="font-headline text-3xl font-bold text-foreground sm:text-4xl">Trusted by Patients and Professionals</h2>
              <p className="mt-4 max-w-2xl mx-auto text-muted-foreground">
                Hear what our users have to say about their experience with NirogTech.
              </p>
            </div>
            <div className="mt-16 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
              {testimonials.map((testimonial) => (
                <Card key={testimonial.name} className="flex flex-col">
                  <CardContent className="pt-6 flex-grow">
                    <p className="italic text-muted-foreground">"{testimonial.text}"</p>
                  </CardContent>
                  <CardHeader className="flex-row items-center gap-4">
                    <Avatar>
                      {testimonial.image && <AvatarImage src={testimonial.image} alt={testimonial.name} />}
                      <AvatarFallback>{testimonial.avatar}</AvatarFallback>
                    </Avatar>
                    <div>
                      <CardTitle className="text-base font-semibold">{testimonial.name}</CardTitle>
                      <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                    </div>
                  </CardHeader>
                </Card>
              ))}
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t">
        <div className="container py-8 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <Logo className="size-6 text-muted-foreground" />
            <span className="text-muted-foreground">
              © {new Date().getFullYear()} NirogTech. All rights reserved.
            </span>
          </div>
          <nav className="flex gap-4">
            <Link href="#" className="text-sm text-muted-foreground hover:text-foreground">Privacy Policy</Link>
            <Link href="#" className="text-sm text-muted-foreground hover:text-foreground">Terms of Service</Link>
            <Link href="#" className="text-sm text-muted-foreground hover:text-foreground">Contact</Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
